package SimpleProgrammingLanguage;

/* Generated By:JavaCC: Do not edit this line. SimpleProgrammingLanguageConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleProgrammingLanguageConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ID = 6;
  /** RegularExpression Id. */
  int OP = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"for\"",
    "\"=\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "<ID>",
    "<OP>",
  };

}
